from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph

def generate_pdf(
    filename,
    protein_name,
    protein_id,
    sequence_length,
    drug_name,
    molecular_weight,
    logp,
    tpsa,
    h_donors,
    h_acceptors,
    lipinski_score,
    lipinski_result
):

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    story.append(Paragraph("<b>AI Drug Discovery Report</b>", styles["Title"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph("<b>Protein Information</b>", styles["Heading2"]))
    story.append(Paragraph(f"Protein File: {protein_name}", styles["Normal"]))
    story.append(Paragraph(f"Protein ID: {protein_id}", styles["Normal"]))
    story.append(Paragraph(f"Sequence Length: {sequence_length}", styles["Normal"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph("<b>Drug Information</b>", styles["Heading2"]))
    story.append(Paragraph(f"Drug File: {drug_name}", styles["Normal"]))
    story.append(Paragraph(f"Molecular Weight: {molecular_weight}", styles["Normal"]))
    story.append(Paragraph(f"LogP: {logp}", styles["Normal"]))
    story.append(Paragraph(f"TPSA: {tpsa}", styles["Normal"]))
    story.append(Paragraph(f"H-Bond Donors: {h_donors}", styles["Normal"]))
    story.append(Paragraph(f"H-Bond Acceptors: {h_acceptors}", styles["Normal"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph("<b>Lipinski Analysis</b>", styles["Heading2"]))
    story.append(Paragraph(f"Score: {lipinski_score}/4", styles["Normal"]))
    story.append(Paragraph(f"Result: {lipinski_result}", styles["Normal"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(
        Paragraph(
            "Generated by AI Drug Discovery Platform",
            styles["Italic"]
        )
    )

    doc.build(story)